apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::678511327499:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-3EYbo8eKYxqZ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::678511327499:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::678511327499:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-02T06:18:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1178"
  uid: 7405153f-a970-4ba1-a907-31be4cb874a0

