apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::678511327499:role/eksctl-roboshop-dev-addon-iamserviceaccount-r-Role1-fQbjgJ4Lhf18
  creationTimestamp: "2026-04-02T11:34:32Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: secret-reader
  namespace: roboshop
  resourceVersion: "55327"
  uid: ecf093c1-f074-4232-b992-f66e51579d82
